/*
 * generated by Xtext 2.13.0
 */
package org.example.xtext.lexertrace


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LexertraceStandaloneSetup extends LexertraceStandaloneSetupGenerated {

	def static void doSetup() {
		new LexertraceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
